### ISSUE TITLE
boost::heap::fibonacci_heap::contains (or equal_range)

### ISSUE THREAD

**Issue by vinipsmaker** [boostorg/heap#34]
Would it be feasible to add `contains()` member function to `boost::heap::fibonacci_heap`? I'm using this structure to store shared pointers that are also tracked in different structures and sometimes I have to check whether a certain element has already been processed.

**Comment by timblechmann** [comment]
not efficiently (i.e. not without an additional lookup table, which is out of the scope of this library)
* consider using boost.intrusive's `treap`
* use a separate lookup table
* find the element in the `begin/end` range
