### ISSUE TITLE
Missing noexcept specifiers

### ISSUE THREAD

**Issue by apolukhin** [boostorg/heap#5]
Move constructors and move assignments of heaps do not throw exceptions, but are not marked with `noexcept`. This leads to regressions when heaps are used in `std::vector`, or when heap is a member of a class with default move constructors/assignments.

Please mark all the nonthrowing methods with `BOOST_NOEXCEPT`, or at least mark move constructors/assignments.

**Comment by timblechmann** [comment]
boost.heap is basically in maintenance mode for me atm, but i'm more than happy to review and merge pull requests!

**Comment by apolukhin** [comment]
OK, I'll try to make it soon.

**Comment by timblechmann** [comment]
thnx for the PR
